version: '3'
volumes:
  static-data:
  media-data:
services:
  django:
    image: custom_image:latest
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
    working_dir: /home/web/django_project
    command: uwsgi --ini /home/web/django_project/uwsgi.ini
    environment:
      DJANGO_SETTINGS_MODULE: mysite.settings
      DEBUG: ${DEBUG:-False}
      SITENAME: ${SITENAME:-localhost}
    volumes:
    - static-data:/home/web/static
    - media-data:/home/web/media
    ports:
    - "8080:8080"

  nginx:
    image: custom_nginx
    build:
      context: nginx
    volumes:
    - static-data:/home/web/static
    - media-data:/home/web/media
    ports:
    - "${HTTP_PORT:-80}:80"
    links:
      - django
